# app/services/memory_service.py

import uuid
from datetime import datetime
from typing import List
from app.services.vector_db import memory_collection


# =====================================================
# STORE MEMORY
# =====================================================

def store_memory(
    grounded_query: str,
    original_question: str,
    vision_summary: str,
    answer: str,
    dependency: str,
):
    """
    Stores conversation memory into ChromaDB.
    Embeddings are automatically generated by Chroma.
    """

    memory_text = f"""
User Question: {original_question}
Dependency: {dependency}
Vision Analysis: {vision_summary}
Assistant Answer: {answer}
"""

    memory_collection.add(
        documents=[memory_text],
        ids=[str(uuid.uuid4())],
        metadatas=[{
            "timestamp": datetime.utcnow().isoformat(),
            "dependency": dependency
        }]
    )


# =====================================================
# SEMANTIC MEMORY RETRIEVAL
# =====================================================

def get_memory(query: str, top_k: int = 2) -> List[str]:
    """
    Performs semantic similarity search in memory collection.
    """

    results = memory_collection.query(
        query_texts=[query],
        n_results=top_k
    )

    if not results or not results.get("documents"):
        return []

    documents = results["documents"][0]

    # Remove empty entries
    documents = [doc for doc in documents if doc.strip()]

    return documents
